// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.20.1
// source: discountService.proto

package discount

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpsertDiscountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title     string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	StartDate *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=startDate,proto3" json:"startDate,omitempty"`
	EndDate   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=endDate,proto3" json:"endDate,omitempty"`
	Rows      []*Row                 `protobuf:"bytes,4,rep,name=rows,proto3" json:"rows,omitempty"`
}

func (x *UpsertDiscountReq) Reset() {
	*x = UpsertDiscountReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_discountService_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertDiscountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertDiscountReq) ProtoMessage() {}

func (x *UpsertDiscountReq) ProtoReflect() protoreflect.Message {
	mi := &file_discountService_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertDiscountReq.ProtoReflect.Descriptor instead.
func (*UpsertDiscountReq) Descriptor() ([]byte, []int) {
	return file_discountService_proto_rawDescGZIP(), []int{0}
}

func (x *UpsertDiscountReq) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpsertDiscountReq) GetStartDate() *timestamppb.Timestamp {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *UpsertDiscountReq) GetEndDate() *timestamppb.Timestamp {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *UpsertDiscountReq) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

type UpsertDiscountRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *UpsertDiscountRes) Reset() {
	*x = UpsertDiscountRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_discountService_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpsertDiscountRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpsertDiscountRes) ProtoMessage() {}

func (x *UpsertDiscountRes) ProtoReflect() protoreflect.Message {
	mi := &file_discountService_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpsertDiscountRes.ProtoReflect.Descriptor instead.
func (*UpsertDiscountRes) Descriptor() ([]byte, []int) {
	return file_discountService_proto_rawDescGZIP(), []int{1}
}

func (x *UpsertDiscountRes) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type GetDiscountedProductIDsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DiscountId string `protobuf:"bytes,1,opt,name=discountId,proto3" json:"discountId,omitempty"`
}

func (x *GetDiscountedProductIDsReq) Reset() {
	*x = GetDiscountedProductIDsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_discountService_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDiscountedProductIDsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiscountedProductIDsReq) ProtoMessage() {}

func (x *GetDiscountedProductIDsReq) ProtoReflect() protoreflect.Message {
	mi := &file_discountService_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiscountedProductIDsReq.ProtoReflect.Descriptor instead.
func (*GetDiscountedProductIDsReq) Descriptor() ([]byte, []int) {
	return file_discountService_proto_rawDescGZIP(), []int{2}
}

func (x *GetDiscountedProductIDsReq) GetDiscountId() string {
	if x != nil {
		return x.DiscountId
	}
	return ""
}

type GetDiscountedProductIDsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductIds []string `protobuf:"bytes,1,rep,name=productIds,proto3" json:"productIds,omitempty"`
}

func (x *GetDiscountedProductIDsRes) Reset() {
	*x = GetDiscountedProductIDsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_discountService_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetDiscountedProductIDsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDiscountedProductIDsRes) ProtoMessage() {}

func (x *GetDiscountedProductIDsRes) ProtoReflect() protoreflect.Message {
	mi := &file_discountService_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDiscountedProductIDsRes.ProtoReflect.Descriptor instead.
func (*GetDiscountedProductIDsRes) Descriptor() ([]byte, []int) {
	return file_discountService_proto_rawDescGZIP(), []int{3}
}

func (x *GetDiscountedProductIDsRes) GetProductIds() []string {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

type PageInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalItems  int32 `protobuf:"varint,1,opt,name=totalItems,proto3" json:"totalItems,omitempty"`
	ItemPerPage int32 `protobuf:"varint,2,opt,name=itemPerPage,proto3" json:"itemPerPage,omitempty"`
	PageNumber  int32 `protobuf:"varint,3,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_discountService_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_discountService_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_discountService_proto_rawDescGZIP(), []int{4}
}

func (x *PageInfo) GetTotalItems() int32 {
	if x != nil {
		return x.TotalItems
	}
	return 0
}

func (x *PageInfo) GetItemPerPage() int32 {
	if x != nil {
		return x.ItemPerPage
	}
	return 0
}

func (x *PageInfo) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

type PageSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemPerPage int32 `protobuf:"varint,1,opt,name=itemPerPage,proto3" json:"itemPerPage,omitempty"`
	PageNumber  int32 `protobuf:"varint,2,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
}

func (x *PageSpec) Reset() {
	*x = PageSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_discountService_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PageSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageSpec) ProtoMessage() {}

func (x *PageSpec) ProtoReflect() protoreflect.Message {
	mi := &file_discountService_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageSpec.ProtoReflect.Descriptor instead.
func (*PageSpec) Descriptor() ([]byte, []int) {
	return file_discountService_proto_rawDescGZIP(), []int{5}
}

func (x *PageSpec) GetItemPerPage() int32 {
	if x != nil {
		return x.ItemPerPage
	}
	return 0
}

func (x *PageSpec) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

type SortCriteriaSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FieldName   string `protobuf:"bytes,1,opt,name=fieldName,proto3" json:"fieldName,omitempty"`
	IsAscending bool   `protobuf:"varint,2,opt,name=isAscending,proto3" json:"isAscending,omitempty"`
}

func (x *SortCriteriaSpec) Reset() {
	*x = SortCriteriaSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_discountService_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SortCriteriaSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SortCriteriaSpec) ProtoMessage() {}

func (x *SortCriteriaSpec) ProtoReflect() protoreflect.Message {
	mi := &file_discountService_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SortCriteriaSpec.ProtoReflect.Descriptor instead.
func (*SortCriteriaSpec) Descriptor() ([]byte, []int) {
	return file_discountService_proto_rawDescGZIP(), []int{6}
}

func (x *SortCriteriaSpec) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

func (x *SortCriteriaSpec) GetIsAscending() bool {
	if x != nil {
		return x.IsAscending
	}
	return false
}

type FilterProductSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SearchText   string `protobuf:"bytes,1,opt,name=searchText,proto3" json:"searchText,omitempty"`
	MinimumPrice int64  `protobuf:"varint,2,opt,name=minimumPrice,proto3" json:"minimumPrice,omitempty"`
	MaximumPrice int64  `protobuf:"varint,3,opt,name=maximumPrice,proto3" json:"maximumPrice,omitempty"`
}

func (x *FilterProductSpec) Reset() {
	*x = FilterProductSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_discountService_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FilterProductSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterProductSpec) ProtoMessage() {}

func (x *FilterProductSpec) ProtoReflect() protoreflect.Message {
	mi := &file_discountService_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterProductSpec.ProtoReflect.Descriptor instead.
func (*FilterProductSpec) Descriptor() ([]byte, []int) {
	return file_discountService_proto_rawDescGZIP(), []int{7}
}

func (x *FilterProductSpec) GetSearchText() string {
	if x != nil {
		return x.SearchText
	}
	return ""
}

func (x *FilterProductSpec) GetMinimumPrice() int64 {
	if x != nil {
		return x.MinimumPrice
	}
	return 0
}

func (x *FilterProductSpec) GetMaximumPrice() int64 {
	if x != nil {
		return x.MaximumPrice
	}
	return 0
}

var File_discountService_proto protoreflect.FileDescriptor

var file_discountService_proto_rawDesc = []byte{
	0x0a, 0x15, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x13, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x4d, 0x6f, 0x64, 0x65,
	0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xbc, 0x01, 0x0a, 0x11, 0x55, 0x70, 0x73, 0x65,
	0x72, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x73, 0x74, 0x61, 0x72, 0x74, 0x44, 0x61, 0x74, 0x65, 0x12, 0x34, 0x0a,
	0x07, 0x65, 0x6e, 0x64, 0x44, 0x61, 0x74, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x07, 0x65, 0x6e, 0x64, 0x44,
	0x61, 0x74, 0x65, 0x12, 0x21, 0x0a, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x0d, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x52, 0x6f, 0x77,
	0x52, 0x04, 0x72, 0x6f, 0x77, 0x73, 0x22, 0x27, 0x0a, 0x11, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74,
	0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x75,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22,
	0x3c, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x64,
	0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a,
	0x0a, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x3c, 0x0a,
	0x1a, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x64, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x73, 0x52, 0x65, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x70,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x73, 0x22, 0x6c, 0x0a, 0x08, 0x50,
	0x61, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74,
	0x61, 0x6c, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x74, 0x65, 0x6d, 0x50,
	0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x69, 0x74,
	0x65, 0x6d, 0x50, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x67,
	0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70,
	0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x4c, 0x0a, 0x08, 0x50, 0x61, 0x67,
	0x65, 0x53, 0x70, 0x65, 0x63, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x74, 0x65, 0x6d, 0x50, 0x65, 0x72,
	0x50, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x69, 0x74, 0x65, 0x6d,
	0x50, 0x65, 0x72, 0x50, 0x61, 0x67, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x61, 0x67,
	0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x52, 0x0a, 0x10, 0x53, 0x6f, 0x72, 0x74, 0x43,
	0x72, 0x69, 0x74, 0x65, 0x72, 0x69, 0x61, 0x53, 0x70, 0x65, 0x63, 0x12, 0x1c, 0x0a, 0x09, 0x66,
	0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x69, 0x73, 0x41,
	0x73, 0x63, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b,
	0x69, 0x73, 0x41, 0x73, 0x63, 0x65, 0x6e, 0x64, 0x69, 0x6e, 0x67, 0x22, 0x7b, 0x0a, 0x11, 0x46,
	0x69, 0x6c, 0x74, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x53, 0x70, 0x65, 0x63,
	0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x65, 0x78, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x61, 0x72, 0x63, 0x68, 0x54, 0x65, 0x78, 0x74,
	0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6d, 0x69, 0x6e, 0x69, 0x6d, 0x75, 0x6d, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x61, 0x78, 0x69, 0x6d, 0x75, 0x6d, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6d, 0x61, 0x78, 0x69,
	0x6d, 0x75, 0x6d, 0x50, 0x72, 0x69, 0x63, 0x65, 0x32, 0xc8, 0x01, 0x0a, 0x0f, 0x44, 0x69, 0x73,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4c, 0x0a, 0x0e,
	0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1b,
	0x2e, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74,
	0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1b, 0x2e, 0x64, 0x69,
	0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x55, 0x70, 0x73, 0x65, 0x72, 0x74, 0x44, 0x69, 0x73,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12, 0x67, 0x0a, 0x17, 0x47, 0x65,
	0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x49, 0x44, 0x73, 0x12, 0x24, 0x2e, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x65, 0x64, 0x50, 0x72,
	0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x24, 0x2e, 0x64, 0x69,
	0x73, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x47, 0x65, 0x74, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x65, 0x64, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x44, 0x73, 0x52, 0x65,
	0x73, 0x22, 0x00, 0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2e, 0x2f, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_discountService_proto_rawDescOnce sync.Once
	file_discountService_proto_rawDescData = file_discountService_proto_rawDesc
)

func file_discountService_proto_rawDescGZIP() []byte {
	file_discountService_proto_rawDescOnce.Do(func() {
		file_discountService_proto_rawDescData = protoimpl.X.CompressGZIP(file_discountService_proto_rawDescData)
	})
	return file_discountService_proto_rawDescData
}

var file_discountService_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_discountService_proto_goTypes = []interface{}{
	(*UpsertDiscountReq)(nil),          // 0: discount.UpsertDiscountReq
	(*UpsertDiscountRes)(nil),          // 1: discount.UpsertDiscountRes
	(*GetDiscountedProductIDsReq)(nil), // 2: discount.GetDiscountedProductIDsReq
	(*GetDiscountedProductIDsRes)(nil), // 3: discount.GetDiscountedProductIDsRes
	(*PageInfo)(nil),                   // 4: discount.PageInfo
	(*PageSpec)(nil),                   // 5: discount.PageSpec
	(*SortCriteriaSpec)(nil),           // 6: discount.SortCriteriaSpec
	(*FilterProductSpec)(nil),          // 7: discount.FilterProductSpec
	(*timestamppb.Timestamp)(nil),      // 8: google.protobuf.Timestamp
	(*Row)(nil),                        // 9: discount.Row
}
var file_discountService_proto_depIdxs = []int32{
	8, // 0: discount.UpsertDiscountReq.startDate:type_name -> google.protobuf.Timestamp
	8, // 1: discount.UpsertDiscountReq.endDate:type_name -> google.protobuf.Timestamp
	9, // 2: discount.UpsertDiscountReq.rows:type_name -> discount.Row
	0, // 3: discount.DiscountService.UpsertDiscount:input_type -> discount.UpsertDiscountReq
	2, // 4: discount.DiscountService.GetDiscountedProductIDs:input_type -> discount.GetDiscountedProductIDsReq
	1, // 5: discount.DiscountService.UpsertDiscount:output_type -> discount.UpsertDiscountRes
	3, // 6: discount.DiscountService.GetDiscountedProductIDs:output_type -> discount.GetDiscountedProductIDsRes
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_discountService_proto_init() }
func file_discountService_proto_init() {
	if File_discountService_proto != nil {
		return
	}
	file_discountModel_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_discountService_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertDiscountReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_discountService_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpsertDiscountRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_discountService_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDiscountedProductIDsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_discountService_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetDiscountedProductIDsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_discountService_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_discountService_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PageSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_discountService_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SortCriteriaSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_discountService_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FilterProductSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_discountService_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_discountService_proto_goTypes,
		DependencyIndexes: file_discountService_proto_depIdxs,
		MessageInfos:      file_discountService_proto_msgTypes,
	}.Build()
	File_discountService_proto = out.File
	file_discountService_proto_rawDesc = nil
	file_discountService_proto_goTypes = nil
	file_discountService_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DiscountServiceClient is the client API for DiscountService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DiscountServiceClient interface {
	UpsertDiscount(ctx context.Context, in *UpsertDiscountReq, opts ...grpc.CallOption) (*UpsertDiscountRes, error)
	GetDiscountedProductIDs(ctx context.Context, in *GetDiscountedProductIDsReq, opts ...grpc.CallOption) (*GetDiscountedProductIDsRes, error)
}

type discountServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscountServiceClient(cc grpc.ClientConnInterface) DiscountServiceClient {
	return &discountServiceClient{cc}
}

func (c *discountServiceClient) UpsertDiscount(ctx context.Context, in *UpsertDiscountReq, opts ...grpc.CallOption) (*UpsertDiscountRes, error) {
	out := new(UpsertDiscountRes)
	err := c.cc.Invoke(ctx, "/discount.DiscountService/UpsertDiscount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discountServiceClient) GetDiscountedProductIDs(ctx context.Context, in *GetDiscountedProductIDsReq, opts ...grpc.CallOption) (*GetDiscountedProductIDsRes, error) {
	out := new(GetDiscountedProductIDsRes)
	err := c.cc.Invoke(ctx, "/discount.DiscountService/GetDiscountedProductIDs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscountServiceServer is the server API for DiscountService service.
type DiscountServiceServer interface {
	UpsertDiscount(context.Context, *UpsertDiscountReq) (*UpsertDiscountRes, error)
	GetDiscountedProductIDs(context.Context, *GetDiscountedProductIDsReq) (*GetDiscountedProductIDsRes, error)
}

// UnimplementedDiscountServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDiscountServiceServer struct {
}

func (*UnimplementedDiscountServiceServer) UpsertDiscount(context.Context, *UpsertDiscountReq) (*UpsertDiscountRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertDiscount not implemented")
}
func (*UnimplementedDiscountServiceServer) GetDiscountedProductIDs(context.Context, *GetDiscountedProductIDsReq) (*GetDiscountedProductIDsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDiscountedProductIDs not implemented")
}

func RegisterDiscountServiceServer(s *grpc.Server, srv DiscountServiceServer) {
	s.RegisterService(&_DiscountService_serviceDesc, srv)
}

func _DiscountService_UpsertDiscount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertDiscountReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscountServiceServer).UpsertDiscount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discount.DiscountService/UpsertDiscount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscountServiceServer).UpsertDiscount(ctx, req.(*UpsertDiscountReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiscountService_GetDiscountedProductIDs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDiscountedProductIDsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscountServiceServer).GetDiscountedProductIDs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/discount.DiscountService/GetDiscountedProductIDs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscountServiceServer).GetDiscountedProductIDs(ctx, req.(*GetDiscountedProductIDsReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _DiscountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "discount.DiscountService",
	HandlerType: (*DiscountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpsertDiscount",
			Handler:    _DiscountService_UpsertDiscount_Handler,
		},
		{
			MethodName: "GetDiscountedProductIDs",
			Handler:    _DiscountService_GetDiscountedProductIDs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "discountService.proto",
}
